server:
  port: 8087
spring:
  application:
    name: springboot-minio
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-file-size: 1000MB #设置单个文件最大长度
      max-request-size: 1000MB #最大请求文件的大小
minio:
  endpoint: 192.168.2.37
  port: 9001
  accessKey: root
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfAMPLEKEY
  secure: false
  bucket-name: commons # 桶名 给了一个默认桶名
  image-size: 10485760 # 图片文件的最大大小
  file-size: 1073741824 # 此处是设定了文件的最大大小